[helpers]

[default]
depends = []

[default.files]
dotter = ""

[default.variables]

[settings]
default_target_type = "automatic"

[zsh.files]
"zsh/.zshrc" = "~/.zshrc"
"zsh/.zshenv" = "~/.zshenv"
"zsh/starship.toml" = "~/.config/starship.toml"

[ghostty.files]
"ghostty/config" = "~/.config/ghostty/config"

[hypr.files]
"hypr/binds.conf" = "~/.config/hypr/binds.conf"
"hypr/hyprland_home.conf" = "~/.config/hypr/hyprland.conf"
"hypr/window_rules.conf" = "~/.config/hypr/window_rules.conf"
"hypr/monitor/home.conf" = "~/.config/hypr/monitor.conf"